sudo: required
services:
  - docker

before_install:
  - docker build -t mkm177/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true mkm177/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-812274920006"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
